### PR TITLE
OSD: add CRSF RSSI dBm, SNR and active antenna items and add RF mode to the LQ item

### PR DESCRIPTION
**Pull request by wvarty**
This PR adds the following OSD elements as properly selectable options:

- RSSIdBm
- SNR
- Active antenna

It also should hopefully auto detect if using CRSF, in order to either show or hide the RF_Mode on the front of LQ.

Note: THIS IS UNTESTED, and is a preliminary PR to get some feedback happening.
I'll test flight all of these out properly over the next few days.
New Project (1)
osd

### CODE REVIEW

**Comment by wvarty** [comment]
Bummer, looks like I grabbed a bunch of other commits accidentally :|

**Review by shellixyz — APPROVED** [review]
Looking good besides the base issue

**Comment by shellixyz** [comment]
I rebased the branch and took the liberty to do a few things:
- use new OSD symbols introduced in #80 
- fix some padding issues
- add an option to chose to display or not the RF mode in the LQ element
- make sure it displays dashes if the TX hasn't been connected

IMG_20220207_200133
IMG_20220207_200322

**Comment by shellixyz** [comment]
I changed the length of the RSSI dBm again to be 4 characters since I guess it can go under -100

**Pull request merged**
